nav:
- README: "README.md"
- "信息控制与计算": "信息控制与计算/README.md"
- "信息电子学物理基础": "信息电子学物理基础/README.md"
- "场波实验": "场波实验/README.md"
- "嵌入式系统原理与设计": "嵌入式系统原理与设计/README.md"
- "数字信号处理综合实验": "数字信号处理综合实验/README.md"
- "数据库系统": "数据库系统/README.md"
- "数电实验": "数电实验/README.md"
- "智能移动系统设计实验": "智能移动系统设计实验/README.md"
- "电子电路实验1": "电子电路实验1/README.md"
- "电子电路实验2": "电子电路实验2/README.md"
- "矩阵论": "矩阵论/README.md"
- "程序设计专题": "程序设计专题/README.md"
- "计算机组成与设计": "计算机组成与设计/README.md"
- "计算机网络": "计算机网络/README.md"
- "通信原理": "通信原理/README.md"
- "通信原理实验": "通信原理实验/README.md"

site_name: ZJU ISEE
theme:
  highlightjs: true
  language: zh
  name: material
